[build]
  command = "npm run build"
  functions = "functions"

[[redirects]]
from = "/*"
to = "/dist/index.html"
status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true