[functions]
  directory = ".netlify/functions"
  external_node_modules = ["express", "serverless-http"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200