[build]
  command = "npm install"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]