[build]
  command = "npm install"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/lambda/:splat"
  status = 200

[functions]
  directory = "."
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http"]