[build]
  publish = "public" 
  command = "npm install"
  base = "/"

[context.production]
  [context.production.environment]
    NODE_ENV = "production"
    API_URL = "https://api.example.com"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    API_URL = "https://api.ronkao.tw"

# 自定義標頭
[[headers]]
  # 設定安全性和快取的 HTTP 標頭
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"